name: Update Code and Clear Cache

on:
  push:
    branches:
      - main

jobs:
  update-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Pull latest code
      run: |
        git pull origin main
        echo "Repository updated"

    - name: Clear cache
      run: |
        rm -rf node_modules
        npm cache clean --force
        echo "Cache cleared"
